In [1]:
import pandas as pd

In [2]:
# Reading few rows to have an idea
vaccinitaly_df = pd.read_csv("tweets_processed.csv",
                             nrows=10,
                             encoding="utf-8",
                             lineterminator='\n')
vaccinitaly_df

,Unnamed: 0,id,created_at,user_id,user_screen_name,geo,place,lang,truncated,text,...,retweeted_user_screen_name,quoted_urls,quoted_hashtags,quoted_created_at,quoted_status_id,quoted_user_screen_name,media,positive,neutral,negative
0,0,1340465356964585474,2020-12-20 01:13:40+00:00,398032197,AnnaMariaCastel,NaN,NaN,it,NaN,NaN,...,antonio_bordin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1340465632177995776,2020-12-20 01:14:46+00:00,1038231816,EdiGirolami,NaN,NaN,it,NaN,NaN,...,DarioBallini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1340465924932063236,2020-12-20 01:15:55+00:00,457762156,BosioFabrizio,NaN,NaN,it,NaN,NaN,...,ImolaOggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1340465989436268547,2020-12-20 01:16:11+00:00,1312802310830125057,CarlottaMarche7,NaN,NaN,it,NaN,NaN,...,Gianmar26145917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1340466102380457984,2020-12-20 01:16:38+00:00,1030696837748060160,AssPiuE,NaN,NaN,it,NaN,NaN,...,piueuofficial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,1340466213240135682,2020-12-20 01:17:04+00:00,1043948268932214786,Ussignur_,NaN,NaN,it,NaN,@maxdantoni E questo Ã¨ quello che dice il Brit...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021140,0.922416,0.056444
6,6,1340466248782655488,2020-12-20 01:17:13+00:00,922839841,MarcoMameli2,NaN,NaN,it,NaN,NaN,...,ImolaOggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1340466401111388162,2020-12-20 01:17:49+00:00,1267671279718535174,Treese09543560,NaN,NaN,und,NaN,ðŸš«ðŸ’‰\n\n#vaccination #vaccinations #vaccinatie...,...,NaN,https://jamanetwork.com/journals/jama/fullarti...,NurembergCode;NaziDoctors;CrimesAgainstHumanit...,Thu Dec 05 09:29:28 +0000 2019,1.202520e+18,PrevGenocide,NaN,0.001386,0.998330,0.000285
8,8,1340466489401503749,2020-12-20 01:18:10+00:00,1249678210314502144,Lulu29786222,NaN,NaN,it,NaN,"Quanta confusione con i vaccini,ci sono gli ef...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001437,0.057905,0.940658
9,9,1340466604149272576,2020-12-20 01:18:37+00:00,833219221,pollong72,NaN,NaN,it,NaN,NaN,...,OpheliaNym,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
vaccinitaly_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  10 non-null     int64
 1   id                          10 non-null     int64
 2   created_at                  10 non-null     object
 3   user_id                     10 non-null     int64
 4   user_screen_name            10 non-null     object
 5   geo                         0 non-null      float64
 6   place                       0 non-null      float64
 7   lang                        10 non-null     object
 8   truncated                   0 non-null      float64
 9   text                        3 non-null      object
 10  retweet_count               10 non-null     int64
 11  likes_count                 10 non-null     int64
 12  retweeted_text              7 non-null      object
 13  user_mentions               8 non-null      object
 14  hashtags                    3 non-null      object
 15  urls                        2 non-null      object
 16  is_quote                    10 non-null     int64
 17  is_reply                    10 non-null     int64
 18  is_original                 10 non-null     int64
 19  is_retweet                  10 non-null     int64
 20  in_reply_to_status_id       1 non-null      float64
 21  in_reply_to_screen_name     1 non-null      object
 22  quoted_text                 1 non-null      object
 23  retweeted_status_id         7 non-null      float64
 24  retweeted_user_screen_name  7 non-null      object
 25  quoted_urls                 1 non-null      object
 26  quoted_hashtags             1 non-null      object
 27  quoted_created_at           1 non-null      object
 28  quoted_status_id            1 non-null      float64
 29  quoted_user_screen_name     1 non-null      object
 30  media                       0 non-null      float64
 31  positive                    3 non-null      float64
 32  neutral                     3 non-null      float64
 33  negative                    3 non-null      float64
dtypes: float64(10), int64(9), object(15)
memory usage: 2.8+ KB

In [4]:
# Selection based on
# https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet
cols = ["id",
        "user_id",
        "user_screen_name",
        "is_original",
        "is_retweet",
        "is_reply",
        "is_quote",
        "retweeted_status_id",
        "in_reply_to_status_id",
        "quoted_status_id",
        "retweet_count",
        "likes_count",
        "user_mentions",
        "urls",
        "quoted_urls"]

df = pd.read_csv("tweets_processed.csv",
                 nrows=1000000,
                 encoding="utf-8",
                 low_memory=False,
                 lineterminator='\n',
                 usecols=cols)

In [5]:
df

,id,user_id,user_screen_name,retweet_count,likes_count,user_mentions,urls,is_quote,is_reply,is_original,is_retweet,in_reply_to_status_id,retweeted_status_id,quoted_urls,quoted_status_id
0,1340465356964585474,398032197,AnnaMariaCastel,14,0,antonio_bordin;,NaN,0,0,0,1,NaN,1.340235e+18,NaN,NaN
1,1340465632177995776,1038231816,EdiGirolami,50,0,DarioBallini;,NaN,0,0,0,1,NaN,1.340372e+18,NaN,NaN
2,1340465924932063236,457762156,BosioFabrizio,279,0,ImolaOggi;,NaN,0,0,0,1,NaN,1.340309e+18,NaN,NaN
3,1340465989436268547,1312802310830125057,CarlottaMarche7,87,0,Gianmar26145917;,NaN,0,0,0,1,NaN,1.340392e+18,NaN,NaN
4,1340466102380457984,1030696837748060160,AssPiuE,2,0,piueuofficial;,NaN,0,0,0,1,NaN,1.340408e+18,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1345315570913304582,132592001,matt_2994,0,0,razorback7851;,NaN,0,1,0,0,1.345315e+18,NaN,NaN,NaN
999996,1345315573463457794,11540552,biif,0,0,cosimo7306;Adnkronos;,NaN,0,1,0,0,1.345289e+18,NaN,NaN,NaN
999997,1345315582598664198,2401375612,stefyste70,0,0,GagliardoneS;,NaN,0,0,0,1,NaN,1.344960e+18,NaN,NaN
999998,1345315588697108480,1326287164741742592,sgurzo76,0,0,fattoquotidiano;,NaN,0,1,0,0,1.345300e+18,NaN,NaN,NaN
999999,1345315589187915776,526692895,pinoalfredos,0,0,carlopaolofesta;,NaN,0,0,0,1,NaN,1.345308e+18,NaN,NaN

In [6]:
# Saving on disk
df.to_csv("data_split.csv", index=False)

In [7]:
# Just reading test
pd.read_csv("data_split.csv",
            encoding="utf-8",
            low_memory=False,
            lineterminator='\n')

,id,user_id,user_screen_name,retweet_count,likes_count,user_mentions,urls,is_quote,is_reply,is_original,is_retweet,in_reply_to_status_id,retweeted_status_id,quoted_urls,quoted_status_id
0,1340465356964585474,398032197,AnnaMariaCastel,14,0,antonio_bordin;,NaN,0,0,0,1,NaN,1.340235e+18,NaN,NaN
1,1340465632177995776,1038231816,EdiGirolami,50,0,DarioBallini;,NaN,0,0,0,1,NaN,1.340372e+18,NaN,NaN
2,1340465924932063236,457762156,BosioFabrizio,279,0,ImolaOggi;,NaN,0,0,0,1,NaN,1.340309e+18,NaN,NaN
3,1340465989436268547,1312802310830125057,CarlottaMarche7,87,0,Gianmar26145917;,NaN,0,0,0,1,NaN,1.340392e+18,NaN,NaN
4,1340466102380457984,1030696837748060160,AssPiuE,2,0,piueuofficial;,NaN,0,0,0,1,NaN,1.340408e+18,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1345315570913304582,132592001,matt_2994,0,0,razorback7851;,NaN,0,1,0,0,1.345315e+18,NaN,NaN,NaN
999996,1345315573463457794,11540552,biif,0,0,cosimo7306;Adnkronos;,NaN,0,1,0,0,1.345289e+18,NaN,NaN,NaN
999997,1345315582598664198,2401375612,stefyste70,0,0,GagliardoneS;,NaN,0,0,0,1,NaN,1.344960e+18,NaN,NaN
999998,1345315588697108480,1326287164741742592,sgurzo76,0,0,fattoquotidiano;,NaN,0,1,0,0,1.345300e+18,NaN,NaN,NaN
999999,1345315589187915776,526692895,pinoalfredos,0,0,carlopaolofesta;,NaN,0,0,0,1,NaN,1.345308e+18,NaN,NaN